language: generic
os: linux
sudo: false

before_install:
  - export PATH=/opt/ghc/8.4.3/bin:/opt/cabal/head/bin:$PATH
  - travis_retry cabal new-update

script:
  - cabal new-build all
  - cabal new-exec -- which foundry

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-8.4.3
    - cabal-install-head
    - libgtk-3-dev

cache:
  directories:
    - ~/.cabal
    - ~/.ghc
